### PR TITLE
Bump lineage-19.1 and don't run repo with lineage-19.1 builds

### PR DESCRIPTION
**Pull request by mikatammi**
* Bump lineage-19.1
* Don't run repo with lineage-19.1 builds either

What was tested: Built and flashed into instantnoodlep (OnePlus 8 Pro) device

### CODE REVIEW

**Review by Atemu — COMMENTED** [review]
The actual change is approved but there's a slight issue with the bump:

Dirs that aren't referenced currently do not get removed. You need to wipe the device and vendor dirs JSONs once because we now use the minimal set of devices. Otherwise the other devices will remain on their old versions.

You'll also need to add your instantnoodlep to the supported devices for that to work. If you've built a ROM from this, it does not have the newest instantnoodlep device or vendor dirs.

**Comment by mikatammi** [comment]
I removed the files and ran the update.sh script again, now it resulted it in lot of removed lines from device and vendon files

**Comment by Atemu** [comment]
The build for your device should no longer function now; you must add it to the supported devices.

Or did you add your device in your own tree only?

**Comment by mikatammi** [comment]
I added the device to my tree only for now, I didn't dare to suggest yet that my instantnoodlep would be added to the list of officially supported devices :D

**Comment by Atemu** [comment]
The list of "supported" devices only exists to gate for devices where we know that the updater does the right thing.

I'd be *more* comfortable if your device was the only supported one in 19 because I haven't tested mine in years at this point.

**Review by Atemu — APPROVED** [review]
This is good enough as is though.

**Pull request merged**
