### PR TITLE
fdroid: use pre-built apk 

### PR DESCRIPTION
**Pull request by Atemu**

### CODE REVIEW

**Comment by Kranzes** [comment]
reason?

**Comment by Atemu** [comment]
Ah, yes should have added that.

The current gradle2nix setup is fragile and cannot be updated. We've been stuck on an old version forever. Until someone contributes a maintainable source build, I'll be maintaining the binary one.

Given that gradle2nix is effectively unmaintained and that it wasn't really built for android in the first place, I don't see that happening any time soon.

**Comment by Atemu** [comment]
I have now deployed this on my daily driver and it's working great on LOS20.

**Comment by CyberShadow** [comment]
The APK URL is now a 404.

I think a more stable mirror is needed.

**Pull request merged**
