### PR TITLE
lineageos: 2022041111 -> 2022110516

### PR DESCRIPTION
**Pull request by Atemu**
Built 18.1 and 19.1 for ~~bacon~~cheeseburger but haven't tested it yet.

Edit: Wrong device.

### CODE REVIEW

**Comment by Atemu** [comment]
CI also fails on master, seems like it was borked externally.

**Comment by Atemu** [comment]
Tested on cheeseburger for the last few days and it's working well.

**Comment by danielfullmer** [comment]
Just checking: does webview work for you?  I tried this with an updated chromium webview and it doesn't appear to be working--"Browser" crashes.  Unsure if it's my updated chromium or lineageos causing this.

**Comment by Atemu** [comment]
Webview works for me. Try clearing your package cache, that can cause issues like this.

**Comment by danielfullmer** [comment]
Hmm, interesting. It's still broken for me on sunfish, both before and after upgrading chromium. Both times I flashed a fresh image via `fastboot update -w`:
```
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl: error preparing webview provider from system server
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl: com.android.server.webkit.WebViewUpdateServiceImpl$WebViewPackageMissingException: Could not find a loadable WebView package
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at com.android.server.webkit.WebViewUpdateServiceImpl.findPreferredWebViewPackage(WebViewUpdateServiceImpl.java:446)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at com.android.server.webkit.WebViewUpdateServiceImpl.prepareWebViewInSystemServer(WebViewUpdateServiceImpl.java:169)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at com.android.server.webkit.WebViewUpdateService.prepareWebViewInSystemServer(WebViewUpdateService.java:129)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at com.android.server.SystemServer.lambda$startOtherServices$3$SystemServer(SystemServer.java:2735)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at com.android.server.SystemServer$$ExternalSyntheticLambda3.run(Unknown Source:2)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at com.android.server.SystemServerInitThreadPool.lambda$submitTask$0$SystemServerInitThreadPool(SystemServerInitThreadPool.java:105)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at com.android.server.SystemServerInitThreadPool$$ExternalSyntheticLambda0.run(Unknown Source:6)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl:      at com.android.internal.util.ConcurrentUtils$1$1.run(ConcurrentUtils.java:65)
05-29 15:00:59.320   937  3098 E WebViewUpdateServiceImpl: No valid provider and no fallback available.
```

**Comment by danielfullmer** [comment]
Follow up: I went back and tested whether webview was even working on the lineaegeos flavor before this PR, just in case this isn't a regression but something I just missed testing previously.  Unfortunately, I can confirm it was the lineageos update caused the issue.

**Comment by Atemu** [comment]
Superseded by https://github.com/nix-community/robotnix/pull/213

**Pull request closed without merging**
